#cart-service.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
data:
  PORT: "3003"
  JWT_SECRET: "your-jwt-secret-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: ecommerce-store
  labels:
    name: Kevin
    batch: "11"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cart-service
          image: cart-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: user-service-config
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - port: 3001
      targetPort: 3001
